### PR TITLE
Include support for PHP 8.

### PR DESCRIPTION
**Pull request by mikebronner**

### CODE REVIEW

**Comment by dmyers** [comment]
Is there anyone out there, @beyondcode?

**Comment by Smankusors** [comment]
it's weird to see the check failed... But the previous PR failed too.... and I can't find any information about it. So.... it's OK....? Are the tests run successfully on local?

anyway, @mpociot please?

**Comment by akalongman** [comment]
@mpociot any update?

**Comment by mpociot** [comment]
Thank you for the PR!

**Pull request merged**
