### PR TITLE
Add check for log files in production

### PR DESCRIPTION
**Pull request by DevDavido**
This check adds the possibility to check if your production environment contains log files (for example from reported exceptions). Ignoring certain files is possible too. Currently some tests are needed 😄

### CODE REVIEW

**Comment by Namoshek** [comment]
Can you explain why this is check beneficial? Personally, I don't see a reason why log files are an indicator for a well set-up environment. But maybe I missed something?

**Comment by DevDavido** [comment]
The primary focus of this check is to see, if there are logged exceptions in production. It should indicate that something went wrong...

**Comment by Namoshek** [comment]
To be honest, I'm not entirely convinced the presence of log files itself is enough of an indicator for exceptions. Wouldn't it make more sense to search for specific patterns like `[CRITICAL]` within the files as well? This way, also files with log entries below the logging level `warn` or `error` could be checked. 

Anyhow, at least checking for a log file size `> 0` would make sense to exclude present, but empty files.

**Comment by mpociot** [comment]
I don’t understand how this check should help me. Is it an issue if I have log files? Or if I don’t have log files in my system?
What if I don’t use file based logging?

**Comment by DevDavido** [comment]
I guess the pull request was a little rushed and not well thought through.

**Pull request closed without merging**
