### PR TITLE
Adds a new RedisCanBeAccessed check

### PR DESCRIPTION
**Pull request by Namoshek**
This check does the same as [`DatabaseCanBeAccessed`](../blob/master/src/Checks/DatabaseCanBeAccessed.php), but for Redis cache servers.

### CODE REVIEW

**Comment by mpociot** [comment]
Thank you for the PR. I'm not sure if this should be enabled by default though since there are a lot of different queue drivers to choose from.
The default setup should - in my opinion - be applicable to every Laravel project without having to modify the config file first.

**Comment by Namoshek** [comment]
I'm absolutely on your side with this and I also tried to think about solutions already, but I'm unsure if it is enough to just document the check in the readme. At least in the current form, the readme is probably not going to be good enough (not all checks are listed, etc). So I had some other ideas as well:

- Add an additional example configuration file containing all checks and options.
- Uncomment checks and configurations we do not recommend as default.
- Document all checks and options (and also the ones without options) nicely in the readme or a separate file.

The last option could look something like this:

| Check | Description | Options |
|--------|----------------------|----------|
| `RedisCanBeAccessed` | Verifies that some supervisor programs are running | - **default_connection** *(boolean, default: `true`)*: if the default connection should be checked <br>- **connections** *(array, list of connection names like `['cache_1', 'cache_2']`, default: `[]`)*: additional connections to check |

**Comment by mpociot** [comment]
My first thought was that we could add a github-pages branch to this repository and have a nice documentation website.
This way we could put every check on a separate site and describe the features, how to configure it, etc.

**Comment by Namoshek** [comment]
I haven't used this feature of GitHub so far, but I'm willing to try it and help with the documentation. Would you prefer to keep this PR open until the documentation is done or do you want me to remove or uncomment the config for the new checks so we can merge them?

**Comment by HDVinnie** [comment]
Would love to see this merged! Very useful check!

**Pull request merged**
